name: K6 Load Test

on: [push]

permissions:
  contents: write

jobs:
  performance-test:
    name: Executar Testes de Carga com K6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4 

      - name: Executar Testes de Carga com K6
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: scripts-aws/aws-test.js
