name: K6 Load Test

on: [push]

permissions:
  contents: write

jobs:
  performance-test:
    name: Executar Testes de Carga com K6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4 

      - name: Executar Testes de Carga com K6
        uses: grafana/k6-action@v0.2.0
        with:
          filename: k6-aws/scripts-aws/aws-test.js

      - name: Organizar Relatório de Testes
        run: |
          mkdir -p report
          mv index.html report/

      - name: Upload do Relatório de Testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes-performance
          path: report
