name: K6 Load Test

on: [push]

permissions:
  contents: write

jobs:
  performance-test:
    name: Executar Testes de Carga com K6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Reposit贸rio
        uses: actions/checkout@v3

      - name: Executar Testes de Carga com K6
        uses: grafana/k6-action@v0.2.0
        with: 
          filename: scripts-aws/aws-test.js

      - name: Organizar Relat贸rio de Testes
        run: |
          mkdir -p report
          mv index.html report/

      - name: Upload do Relat贸rio de Testes
        uses: actions/upload-artifact@v3
        with: 
          name: relatorio-testes-performance
          path: report

      - name: Publicar Relat贸rio no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: report
